### ISSUE TITLE
Query Result does not recognize when the redis connection has decode_responses=True

### ISSUE THREAD

**Issue by schwab** [RedisGraph/redisgraph-py#20]
If the underlying redis connection object has been initialized with decode_responses=True, then redis graph throws an exception in the QueryResult_get_value @staticmethod attempting to  decode stat details.

The workaround at this point is to always use decode_responses=False (the default) for any redis connction the that is also used for redisgraph queries; however, this complicates applications which use redis both key_value and redis graph at the same time since then at least 2 connections to the redis server must be maintained (4 if you are using slave and master servers for read/write respectively).

NOTE, this issue was moved from redisgraph as it's actually a problem in python library.

**Comment by swilly22** [comment]
Hi @schwab 
Just to add to the above, the issue occurs when using Python3

`Traceback (most recent call last):
  File "test.py", line 17, in <module>
    redis_graph.commit()
  File "/usr/local/lib/python3.6/dist-packages/redisgraph/client.py", line 136, in commit
    return self.query(query)
  File "/usr/local/lib/python3.6/dist-packages/redisgraph/client.py", line 149, in query
    return QueryResult(result_set, statistics)
  File "/usr/local/lib/python3.6/dist-packages/redisgraph/query_result.py", line 17, in __init__
    self.parsed_statistics = self._retrieve_data_from_statistics(statistics)
  File "/usr/local/lib/python3.6/dist-packages/redisgraph/query_result.py", line 45, in _retrieve_data_from_statistics
    self.LABELS_ADDED: self._get_value(self.LABELS_ADDED, statistics),
  File "/usr/local/lib/python3.6/dist-packages/redisgraph/query_result.py", line 57, in _get_value
    stat = stat.decode()
AttributeError: 'str' object has no attribute 'decode'`

**Comment by swilly22** [comment]
#27
