### ISSUE TITLE
Please confirm Sentinel

### ISSUE THREAD

**Issue by styk-tv** [RedisGraph/redisgraph-py#29]
As I'm working on RedisGraph issue [#430](https://github.com/RedisLabsModules/RedisGraph/issues/430) I confirmed Sentinel `sentinel.master_for` and `sentinel.slave_for` return proper types:

```
>>> type(slave)
<class 'redis.client.Redis'>
>>> type(redis_graph)
<class 'redisgraph.client.Graph'>
```

but something makes it blow up. could anyone please confirm that client returned from `slave_for / master_for` works correctly when fed into redisgraph?

Example code i'm using:
```
from redis.sentinel import Sentinel
from redisgraph import Node, Edge, Graph

sentinel = Sentinel([('localhost', 26379)])
slave = sentinel.slave_for('mymaster', socket_timeout=0.3)

redis_graph = Graph('bulk', slave)
query = "MATCH (t:Tag {name: 'odin'}) RETURN t"
result = redis_graph.query(query)
result.pretty_print()
```

results in exception:
```
Traceback (most recent call last):
  File "sentinel_test.py", line 9, in <module>
    result = redis_graph.query(query)
  File "/usr/local/lib/python3.7/site-packages/redisgraph/client.py", line 155, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/sentinel.py", line 46, in connect
    for slave in self.connection_pool.rotate_slaves():
  File "/usr/local/lib/python3.7/site-packages/redis/sentinel.py", line 122, in rotate_slaves
    yield self.get_master_address()
  File "/usr/local/lib/python3.7/site-packages/redis/sentinel.py", line 100, in get_master_address
    self.service_name)
  File "/usr/local/lib/python3.7/site-packages/redis/sentinel.py", line 203, in discover_master
    masters = sentinel.sentinel_masters()
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1062, in sentinel_masters
    return self.execute_command('SENTINEL MASTERS')
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTERS`,
```

tested with versions:
```
Python 2.7.15
Python 3.7.2

redis==3.2.1
redisgraph==1.7
```

**Comment by swilly22** [comment]
@styk-tv thanks for reporting, I'm looking into it.

**Comment by swilly22** [comment]
This is the setup I've tested:
A single master M running on port 7000
A single slave C running on port 7001 replicating M.
Sentinel S configuration: `sentinel monitor mymaster 127.0.0.1 7000 1`

I've created a graph G on M: `GRAPH.QUERY G "create ()"`

Using the script you've posted:
`from redis.sentinel import Sentinel
from redisgraph import Node, Edge, Graph
sentinel = Sentinel([('localhost', 26379)])
slave = sentinel.slave_for('mymaster', socket_timeout=0.3)
redis_graph = Graph('G', slave)
query = "MATCH (x) RETURN x"
result = redis_graph.query(query)
result.pretty_print()`

output:
python test.py
+---+
| x |
+---+
|   |
+---+

Which is what I would expect.

**Comment by styk-tv** [comment]
Thanks Roi, all good. I should stop doing these things at 3 in the morning. Typo.
